### ISSUE TITLE
Essential laziness

### ISSUE THREAD

**Issue by polytypic** [paulyoung/purescript-prettier-printer#4]
Wadler notes in his [article](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf), page 10, that

> It is essential for efficiency that the inner computation of `best` is performed lazily. 

Is the computation on [this](https://github.com/paulyoung/purescript-prettier-printer/blob/a0ee23b7a5ad041bba6a04af59e7ca01ce605231/src/Prettier/Printer.purs#L105) line, in particular, lazy?

Documents with `n` unions can be constructed that take `Theta(n)` time with the original lazy algorithm and `Theta(n^2)` time with an incorrect strict algorithm.

**Comment by paulyoung** [comment]
@polytypic thanks for reporting this! Please let me know if you have any other concerns.
