### ISSUE TITLE
Add to package set?

### ISSUE THREAD

**Issue by joneshf** [paulyoung/purescript-prettier-printer#9]
Are you interested in putting this in the canonical package set? I'll do the leg work if so. If not, feel free to close this issue.

**Comment by paulyoung** [comment]
Sounds great, please do!

**Comment by paulyoung** [comment]
@joneshf anything I can do to help here?

**Comment by joneshf** [comment]
Sorry, I kind of gave up using psc-package shortly after opening this issue and forgot about it :sweat_smile:. Making a PR now.

**Comment by joneshf** [comment]
It was just merged into `master`. Still need a tag, but that's up to the package-sets repo now.

**Comment by paulyoung** [comment]
Thanks, and nice job on Purcel!
